# Generated by Django 5.2.15 on 2026-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canhotos", "0005_canhoto_divisoria"),
        ("notas", "0002_notafiscal_destinatario_valor_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="canhoto",
            name="notas_atendidas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Notas Fiscais cobertas por esta folha divisória, atribuídas manualmente.",
                related_name="canhotos_divisoria",
                to="notas.notafiscal",
                verbose_name="Notas Fiscais Atendidas (Divisória)",
            ),
        ),
    ]
